### ISSUE TITLE
The KaTex plugin should be to adapted to Crypsis editor.

### ISSUE THREAD

**Issue by rich20** [svanschu/Joomla-Tex-Tools#1]
Crypsis is the new default template from Kunena. It shows in the editor only a invisible symbol. On click on it the code will not inserted in the text field.

**Comment by svanschu** [comment]
the plugin works, but preview still have issues.

**Comment by Mightymax44** [comment]
I installed the last master for kunena and the icon does not appear in the editor on kunena 5.0.13 but your plugins work except preview

**Comment by svanschu** [comment]
Thx, those are indeed the problems which need to be cracking down.

**Comment by Mightymax44** [comment]
i solved my problem:
-upload tex.png /components/com_kunena/template/crypsis/assets/images
and i edit my custom.less in the backend of kunena crypsis with this code:
.markItUp .texbutton a {
	background-image : url(assets/images/tex.png);
}
it works perfectly.

But the code is center to the message, it'snt very beautiful with the text.

I propose the fr version on github

Thanks

**Comment by svanschu** [comment]
Cool thx.

feel free to make a pull request. For all your changes.

Just hadn't the time to do it on my own.
