### ISSUE TITLE
Problem with Jatex 1.5 on Joomla 4.2.8

### ISSUE THREAD

**Issue by helour** [svanschu/Joomla-Tex-Tools#21]
Unfortunately, the extension does not work. Firefox browser reports this error:
Source “https://.../media/plg_jatex/js/mathjax/tex-mml-” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)

**Comment by svanschu** [comment]
Hi, thx for rais this issue.

My demo page is still on J3 and there it works for me, could you check if it works for you there too? https://demo.schultschik.com/

Did this happen after an update or did you install JaTeX into an existing J4.2.8?

**Comment by helour** [comment]
I have upgraded Joomla from 3 to 4 and then installed JaTeX. In Joomla 3 I had some other latex plugin. I don't remember its name, it was uninstalled before the update.

On your website everything is normal (just one unhelpful warning):

![Screenshot](https://user-images.githubusercontent.com/79715809/220110231-1f332e64-4280-40ac-99c2-e573afae60ba.png)

**Comment by helour** [comment]
Today, without changing anything, the plugin works normally. I just had to re-enable the plugin. I don't understand. Please close or delete this issue. Sorry for the inconvenience.

**Comment by svanschu** [comment]
Thank you anyway for reporting. It is good to know, that someone is using the extension and the work is it worth.

If your happy in future with the extension I'm happy about any support.
